#!/usr/bin/env bash

set -eou pipefail

. oks-lib.sh

info "Generating keys from keyspecs ..."
oks hsm generate --auth-method cdr

info "Initializing CAs for keyspecs ..."
oks ca --auth-method cdr initialize

info "Signing requests intermediates & debug auth credentials"
oks ca --auth-method cdr sign
